version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  deploy_preprod:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main

jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          from: out
          to: "s3://coedit-test"
